[workspace]
# path of the git-cliff configuration
changelog_config = "cliff.toml"

# enable changelog updates
changelog_update = true

# update dependencies with `cargo update`
dependencies_update = true

# Enable git releases for all packages by default
git_release_enable = true

# Enable git tags for all packages by default
git_tag_enable = true

# creates the git release as draft
git_release_draft = true

# If true, creates the release PR as a draft.
pr_draft = true

# labels for the release PR
pr_labels = ["release"]

# disallow updating repositories with uncommitted changes
allow_dirty = false

# disallow packaging with uncommitted changes
publish_allow_dirty = false